spring:
  application:
    name: core-service

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

  data:
    mongodb:
      authentication-database: admin
      username: data-user
      password: data-pass
      database: data-service-db
      port: 27017
      host: localhost
  kafka:
    consumer:
      bootstrap-servers: ${kafka.hostname:127.0.0.1}:9092
      group-id: data-service-group
      auto-offset-reset: earliest
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.type.mapping: 'StatisticModel:net.betvictor.dataservice.kafka.model.StatisticModel'
    listener:
      concurrency: 4

server:
  port : 8081